env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
settings: {
  "import/resolver": {
    "node": {
      "extensions": [ ".js", ".ts" ]
    }
  }
}
plugins:
  - '@typescript-eslint'
rules: {
  no-console: 'off',
  max-len: [
    'error', {
      code: 120
    }
  ],
  "import/extensions": [
    "error",
    "ignorePackages",
    {
      "js": "never",
      "ts": "never"
    }
  ],
  "no-shadow": "off",
  "@typescript-eslint/no-shadow": [ "error" ],
  "no-unused-vars": "off",
  "@typescript-eslint/no-unused-vars": "error"
}
